[package]
name = "circuit"
version = "0.1.0"
edition = "2021"
default-run = "circuit"

[lib]
name = "circuit"
path = "src/lib.rs"

[[bin]]
name = "circuit"
path = "src/main.rs"

[[bin]]
name = "generate_proofs"
path = "scripts/generate_proofs.rs"

[[bench]]
name = "benchmarking"
harness = false

[dev-dependencies]
criterion = "0.5"

[dependencies]
rayon = "1.5"
tiny-keccak = "2.0"
num-bigint = "0.4"
num-traits = "0.2"
log = "0.4"
env_logger = "0.10"
uint = "0.9.5"
ark-ff = "0.4.2"
ark-bn254 = "0.4.0"
ark-groth16 = "0.4.0"
ark-relations = "0.4.0"
ark-std = "0.4.0"
ark-serialize = "0.4.2"
ark-snark = "0.4.0"
ark-ec = "0.4.0"
ark-r1cs-std = "0.4.0"
primitive-types = "0.12"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
ethnum = "1.5.0"
expander_compiler = { git = "https://github.com/PolyhedraZK/ExpanderCompilerCollection", branch = "dev" }
arith = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
mpi_config = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
gkr_field_config = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
expander_config = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev", package = "config" }
expander_circuit = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev", package = "circuit" }
gkr = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
gf2 = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
mersenne31 = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
expander_transcript = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev", package = "transcript" }
crosslayer_prototype = { git = "https://github.com/PolyhedraZK/Expander", branch = "dev" }
circuit-std-rs = { git = "https://github.com/PolyhedraZK/ExpanderCompilerCollection", branch = "dev" }
halo2curves = { git = "https://github.com/PolyhedraZK/halo2curves", default-features = false, features = ["bits"] }